Fix build linux/android in release (#15163)
## What does this PR do?

Fixes Linux and android on release configurations. `TaskGraphEvent::m_label` is only used inside `AZ_Assert` statements, so it was warning as not used in release, causing build to fail.

Marking as well `test_BasicEditorWorkflows_LevelEntityComponentCRUD` as xfail since it's regularly failing affecting the speed to submit bug fixes to stabilization branch. (#15172)

Fixed also the following error introduced in #15112 (tagging @galibzon)
````
/data/workspace/o3de/Gems/RemoteTools/Code/Source/RemoteToolsSystemComponent.cpp:568:14: error: variable 'hasActiveConnection' set but not used [-Werror,-Wunused-but-set-variable]
        bool hasActiveConnection = false;
              ^
````

## How was this PR tested?

Built Linux and android on release successfully.

Signed-off-by: moraaar <moraaar@amazon.com>